apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: test-service
    type: backend-service
  name: test-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test-service
        type: backend-service
    spec:
      containers:
      - image: quay.io/loganbfisher/test-service
        name: test-service
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 3000
           name: app
