apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-service
    type: backend-service
  name: test-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    name: test-service
    type: backend-service
